services:
  chall:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "44444:1337"
    environment:
      - TZ=Asia/Seoul
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
