FROM ubuntu:latest

ENV user robot
ENV port 4997

ENV TERM xterm

RUN echo "Acquire::Check-Valid-Until \"false\";\nAcquire::Check-Date \"false\";" | cat > /etc/apt/apt.conf.d/10no--check-valid-until

RUN apt-get update 
RUN apt-get install -y socat
RUN apt-get install -y python3 python3-pip

RUN adduser $user


ADD ./robot.py /home/$user/robot.py
ADD ./run.sh /home/$user/run.sh


RUN chown -R root:root /home/$user/
RUN chown root:$user /home/$user/robot.py
RUN chown root:$user /home/$user/run.sh

RUN chmod 777 /home/$user
RUN chmod 755 /home/$user/robot.py
RUN chmod 755 /home/$user/run.sh

WORKDIR /home/$user/
USER $user
EXPOSE $port
CMD socat TCP-LISTEN:$port,reuseaddr,fork EXEC:./run.sh,stderr


