version: '3'

services:
    lottery:
        container_name: lottery
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "15252:15252"
            - "15353:15353"